### ISSUE TITLE
Create user home page

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v51-tier3-team-35#31]
**User story description**
As an authenticated user, I want to see a page that has a list of my adventures, prioritized by date so I can tap on a trip and review or or continue editing/collaborating.

Stretch goal: the list of adventures has icons or badges indicating some kind of change

**Tasks**
- [x] UI: create the user home page, which includes a list of adventures (by name) and render data from the backend
- [x] Allow user to click a button to create a new adventure. Take them to the "create adventure screen"
- [x] Create any backend api endpoints
- [x] Update any other components that should link or redirect to this home page

**Acceptance Criteria**
This is done when:
- Users who log in, or sign up successfully are immediately redirected to this home page
- Home page fetches trips and lists them in the appropriate order
- If a trip is in the past and is completed, it is readonly.
