### ISSUE TITLE
TODO for V2 After release

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v51-tier3-team-35#58]
- [x] #62
- [ ] Clean up styling and try to get a consistent style. Do we want darkmode?
- [x] Update notifications to make them more robust
- [ ] For comments, work on a feature that auto fetches and updates new comments that appear in the thread
- [x] Allow the canvas creator user to delete a whole adventure canvas
- [ ] Come up with a permissions structure to indicate the amount of read/write access permissions a invitee has on a canvas
- [x] #63
- [ ] Create user profiles, allow image uploading

I'll convert these into cards.
